### ISSUE TITLE
No need to add +1 while generating training data

### ISSUE THREAD

**Issue by snji-khjuria** [sudharsan13296/Word2vec-from-scratch#1]
len(sentence)) seems fine 
_for nb_word in sentence[max(word_index - WINDOW_SIZE, 0) : min(word_index + WINDOW_SIZE, **len(sentence)) + 1**] :_ because we have to go at max of len(sentence).
Please correct me if I am wrong.

**Comment by bobbercheng** [comment]
@snji-khjuria 
Python will use max of len if index go out. min(word_index + WINDOW_SIZE, **len(sentence)) + 1** is to get the index for right nb.
